// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * HostPortRange defines a range of host ports that will be enabled by a policy for pods to use.  It requires both the start and end to be defined. Deprecated: use HostPortRange from policy API Group instead.
 * @export
 * @interface ExtensionsV1beta1HostPortRange
 */
export default interface ExtensionsV1beta1HostPortRange extends KubeObject {
  /**
   * max is the end of the range, inclusive.
   * @type {number}
   * @memberof ExtensionsV1beta1HostPortRange
   */
  max: number

  /**
   * min is the start of the range, inclusive.
   * @type {number}
   * @memberof ExtensionsV1beta1HostPortRange
   */
  min: number
}
