// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * CustomResourceDefinitionNames indicates the names to serve this CustomResourceDefinition
 * @export
 * @interface V1beta1CustomResourceDefinitionNames
 */
export default interface V1beta1CustomResourceDefinitionNames extends KubeObject {
  /**
   * Categories is a list of grouped resources custom resources belong to (e.g. \'all\')
   * @type {Array<string>}
   * @memberof V1beta1CustomResourceDefinitionNames
   */
  categories?: Array<string>

  /**
   * Kind is the serialized kind of the resource.  It is normally CamelCase and singular.
   * @type {string}
   * @memberof V1beta1CustomResourceDefinitionNames
   */
  kind: string

  /**
   * ListKind is the serialized kind of the list for this resource.  Defaults to <kind>List.
   * @type {string}
   * @memberof V1beta1CustomResourceDefinitionNames
   */
  listKind?: string

  /**
   * Plural is the plural name of the resource to serve.  It must match the name of the CustomResourceDefinition-registration too: plural.group and it must be all lowercase.
   * @type {string}
   * @memberof V1beta1CustomResourceDefinitionNames
   */
  plural: string

  /**
   * ShortNames are short names for the resource.  It must be all lowercase.
   * @type {Array<string>}
   * @memberof V1beta1CustomResourceDefinitionNames
   */
  shortNames?: Array<string>

  /**
   * Singular is the singular name of the resource.  It must be all lowercase  Defaults to lowercased <kind>
   * @type {string}
   * @memberof V1beta1CustomResourceDefinitionNames
   */
  singular?: string
}
