// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import V1LabelSelector from './V1LabelSelector'
import V1PodTemplateSpec from './V1PodTemplateSpec'
import V1beta2DaemonSetUpdateStrategy from './V1beta2DaemonSetUpdateStrategy'

/**
 * DaemonSetSpec is the specification of a daemon set.
 * @export
 * @interface V1beta2DaemonSetSpec
 */
export default interface V1beta2DaemonSetSpec extends KubeObject {
  /**
   * The minimum number of seconds for which a newly created DaemonSet pod should be ready without any of its container crashing, for it to be considered available. Defaults to 0 (pod will be considered available as soon as it is ready).
   * @type {number}
   * @memberof V1beta2DaemonSetSpec
   */
  minReadySeconds?: number

  /**
   * The number of old history to retain to allow rollback. This is a pointer to distinguish between explicit zero and not specified. Defaults to 10.
   * @type {number}
   * @memberof V1beta2DaemonSetSpec
   */
  revisionHistoryLimit?: number

  /**
   *
   * @type {V1LabelSelector}
   * @memberof V1beta2DaemonSetSpec
   */
  selector: V1LabelSelector

  /**
   *
   * @type {V1PodTemplateSpec}
   * @memberof V1beta2DaemonSetSpec
   */
  template: V1PodTemplateSpec

  /**
   *
   * @type {V1beta2DaemonSetUpdateStrategy}
   * @memberof V1beta2DaemonSetSpec
   */
  updateStrategy?: V1beta2DaemonSetUpdateStrategy
}
