// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import V1beta1CustomResourceDefinitionCondition from './V1beta1CustomResourceDefinitionCondition'
import V1beta1CustomResourceDefinitionNames from './V1beta1CustomResourceDefinitionNames'

/**
 * CustomResourceDefinitionStatus indicates the state of the CustomResourceDefinition
 * @export
 * @interface V1beta1CustomResourceDefinitionStatus
 */
export default interface V1beta1CustomResourceDefinitionStatus extends KubeObject {
  /**
   *
   * @type {V1beta1CustomResourceDefinitionNames}
   * @memberof V1beta1CustomResourceDefinitionStatus
   */
  acceptedNames: V1beta1CustomResourceDefinitionNames

  /**
   * Conditions indicate state for particular aspects of a CustomResourceDefinition
   * @type {Array<V1beta1CustomResourceDefinitionCondition>}
   * @memberof V1beta1CustomResourceDefinitionStatus
   */
  conditions: Array<V1beta1CustomResourceDefinitionCondition>

  /**
   * StoredVersions are all versions of CustomResources that were ever persisted. Tracking these versions allows a migration path for stored versions in etcd. The field is mutable so the migration controller can first finish a migration to another version (i.e. that no old objects are left in the storage), and then remove the rest of the versions from this list. None of the versions in this list can be removed from the spec.Versions field.
   * @type {Array<string>}
   * @memberof V1beta1CustomResourceDefinitionStatus
   */
  storedVersions: Array<string>
}
