// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * Adds and removes POSIX capabilities from running containers.
 * @export
 * @interface V1Capabilities
 */
export default interface V1Capabilities extends KubeObject {
  /**
   * Added capabilities
   * @type {Array<string>}
   * @memberof V1Capabilities
   */
  add?: Array<string>

  /**
   * Removed capabilities
   * @type {Array<string>}
   * @memberof V1Capabilities
   */
  drop?: Array<string>
}
