// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.11
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import V1DeploymentStrategy from './V1DeploymentStrategy'
import V1LabelSelector from './V1LabelSelector'
import V1PodTemplateSpec from './V1PodTemplateSpec'

/**
 * DeploymentSpec is the specification of the desired behavior of the Deployment.
 * @export
 * @interface V1DeploymentSpec
 */
export default interface V1DeploymentSpec extends KubeObject {
  /**
   * Minimum number of seconds for which a newly created pod should be ready without any of its container crashing, for it to be considered available. Defaults to 0 (pod will be considered available as soon as it is ready)
   * @type {number}
   * @memberof V1DeploymentSpec
   */
  minReadySeconds?: number

  /**
   * Indicates that the deployment is paused.
   * @type {boolean}
   * @memberof V1DeploymentSpec
   */
  paused?: boolean

  /**
   * The maximum time in seconds for a deployment to make progress before it is considered to be failed. The deployment controller will continue to process failed deployments and a condition with a ProgressDeadlineExceeded reason will be surfaced in the deployment status. Note that progress will not be estimated during the time a deployment is paused. Defaults to 600s.
   * @type {number}
   * @memberof V1DeploymentSpec
   */
  progressDeadlineSeconds?: number

  /**
   * Number of desired pods. This is a pointer to distinguish between explicit zero and not specified. Defaults to 1.
   * @type {number}
   * @memberof V1DeploymentSpec
   */
  replicas?: number

  /**
   * The number of old ReplicaSets to retain to allow rollback. This is a pointer to distinguish between explicit zero and not specified. Defaults to 10.
   * @type {number}
   * @memberof V1DeploymentSpec
   */
  revisionHistoryLimit?: number

  /**
   *
   * @type {V1LabelSelector}
   * @memberof V1DeploymentSpec
   */
  selector: V1LabelSelector

  /**
   *
   * @type {V1DeploymentStrategy}
   * @memberof V1DeploymentSpec
   */
  strategy?: V1DeploymentStrategy

  /**
   *
   * @type {V1PodTemplateSpec}
   * @memberof V1DeploymentSpec
   */
  template: V1PodTemplateSpec
}
