// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * EventSeries contain information on series of events, i.e. thing that was/is happening continuously for some time.
 * @export
 * @interface V1EventSeries
 */
export default interface V1EventSeries extends KubeObject {
  /**
   * Number of occurrences in this series up to the last heartbeat time
   * @type {number}
   * @memberof V1EventSeries
   */
  count?: number

  /**
   * Time of the last occurrence observed
   * @type {Date}
   * @memberof V1EventSeries
   */
  lastObservedTime?: Date

  /**
   * State of this Series: Ongoing or Finished
   * @type {string}
   * @memberof V1EventSeries
   */
  state?: string
}
