// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.11
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * HostAlias holds the mapping between IP and hostnames that will be injected as an entry in the pod\'s hosts file.
 * @export
 * @interface V1HostAlias
 */
export default interface V1HostAlias extends KubeObject {
  /**
   * Hostnames for the above IP address.
   * @type {Array<string>}
   * @memberof V1HostAlias
   */
  hostnames?: Array<string>

  /**
   * IP address of the host file entry.
   * @type {string}
   * @memberof V1HostAlias
   */
  ip?: string
}
