// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import V1SecretReference from './V1SecretReference'

/**
 * ISCSIPersistentVolumeSource represents an ISCSI disk. ISCSI volumes can only be mounted as read/write once. ISCSI volumes support ownership management and SELinux relabeling.
 * @export
 * @interface V1ISCSIPersistentVolumeSource
 */
export default interface V1ISCSIPersistentVolumeSource extends KubeObject {
  /**
   * whether support iSCSI Discovery CHAP authentication
   * @type {boolean}
   * @memberof V1ISCSIPersistentVolumeSource
   */
  chapAuthDiscovery?: boolean

  /**
   * whether support iSCSI Session CHAP authentication
   * @type {boolean}
   * @memberof V1ISCSIPersistentVolumeSource
   */
  chapAuthSession?: boolean

  /**
   * Filesystem type of the volume that you want to mount. Tip: Ensure that the filesystem type is supported by the host operating system. Examples: \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified. More info: https://kubernetes.io/docs/concepts/storage/volumes#iscsi
   * @type {string}
   * @memberof V1ISCSIPersistentVolumeSource
   */
  fsType?: string

  /**
   * Custom iSCSI Initiator Name. If initiatorName is specified with iscsiInterface simultaneously, new iSCSI interface <target portal>:<volume name> will be created for the connection.
   * @type {string}
   * @memberof V1ISCSIPersistentVolumeSource
   */
  initiatorName?: string

  /**
   * Target iSCSI Qualified Name.
   * @type {string}
   * @memberof V1ISCSIPersistentVolumeSource
   */
  iqn: string

  /**
   * iSCSI Interface Name that uses an iSCSI transport. Defaults to \'default\' (tcp).
   * @type {string}
   * @memberof V1ISCSIPersistentVolumeSource
   */
  iscsiInterface?: string

  /**
   * iSCSI Target Lun number.
   * @type {number}
   * @memberof V1ISCSIPersistentVolumeSource
   */
  lun: number

  /**
   * iSCSI Target Portal List. The Portal is either an IP or ip_addr:port if the port is other than default (typically TCP ports 860 and 3260).
   * @type {Array<string>}
   * @memberof V1ISCSIPersistentVolumeSource
   */
  portals?: Array<string>

  /**
   * ReadOnly here will force the ReadOnly setting in VolumeMounts. Defaults to false.
   * @type {boolean}
   * @memberof V1ISCSIPersistentVolumeSource
   */
  readOnly?: boolean

  /**
   *
   * @type {V1SecretReference}
   * @memberof V1ISCSIPersistentVolumeSource
   */
  secretRef?: V1SecretReference

  /**
   * iSCSI Target Portal. The Portal is either an IP or ip_addr:port if the port is other than default (typically TCP ports 860 and 3260).
   * @type {string}
   * @memberof V1ISCSIPersistentVolumeSource
   */
  targetPortal: string
}
