// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.11
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'
import V1JobSpec from './V1JobSpec'
import V1JobStatus from './V1JobStatus'
import V1ObjectMeta from './V1ObjectMeta'

/**
 * Job represents the configuration of a single job.
 * @export
 * @interface V1Job
 */
export default interface V1Job extends KubeObject {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
   * @type {string}
   * @memberof V1Job
   */
  apiVersion?: string

  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
   * @type {string}
   * @memberof V1Job
   */
  kind?: string

  /**
   *
   * @type {V1ObjectMeta}
   * @memberof V1Job
   */
  metadata?: V1ObjectMeta

  /**
   *
   * @type {V1JobSpec}
   * @memberof V1Job
   */
  spec?: V1JobSpec

  /**
   *
   * @type {V1JobStatus}
   * @memberof V1Job
   */
  status?: V1JobStatus
}
