// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * LimitRangeItem defines a min/max usage limit for any resource that matches on kind.
 * @export
 * @interface V1LimitRangeItem
 */
export default interface V1LimitRangeItem extends KubeObject {
  /**
   * Default resource requirement limit value by resource name if resource limit is omitted.
   * @type {{ [key: string]: string; }}
   * @memberof V1LimitRangeItem
   */
  _default?: { [key: string]: string }

  /**
   * DefaultRequest is the default resource requirement request value by resource name if resource request is omitted.
   * @type {{ [key: string]: string; }}
   * @memberof V1LimitRangeItem
   */
  defaultRequest?: { [key: string]: string }

  /**
   * Max usage constraints on this kind by resource name.
   * @type {{ [key: string]: string; }}
   * @memberof V1LimitRangeItem
   */
  max?: { [key: string]: string }

  /**
   * MaxLimitRequestRatio if specified, the named resource must have a request and limit that are both non-zero where limit divided by request is less than or equal to the enumerated value; this represents the max burst for the named resource.
   * @type {{ [key: string]: string; }}
   * @memberof V1LimitRangeItem
   */
  maxLimitRequestRatio?: { [key: string]: string }

  /**
   * Min usage constraints on this kind by resource name.
   * @type {{ [key: string]: string; }}
   * @memberof V1LimitRangeItem
   */
  min?: { [key: string]: string }

  /**
   * Type of resource that this limit applies to.
   * @type {string}
   * @memberof V1LimitRangeItem
   */
  type?: string
}
