// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.11
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * PodReadinessGate contains the reference to a pod condition
 * @export
 * @interface V1PodReadinessGate
 */
export default interface V1PodReadinessGate extends KubeObject {
  /**
   * ConditionType refers to a condition in the pod\'s condition list with matching type.
   * @type {string}
   * @memberof V1PodReadinessGate
   */
  conditionType: string
}
