// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.11
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * SELinuxOptions are the labels to be applied to the container
 * @export
 * @interface V1SELinuxOptions
 */
export default interface V1SELinuxOptions extends KubeObject {
  /**
   * Level is SELinux level label that applies to the container.
   * @type {string}
   * @memberof V1SELinuxOptions
   */
  level?: string

  /**
   * Role is a SELinux role label that applies to the container.
   * @type {string}
   * @memberof V1SELinuxOptions
   */
  role?: string

  /**
   * Type is a SELinux type label that applies to the container.
   * @type {string}
   * @memberof V1SELinuxOptions
   */
  type?: string

  /**
   * User is a SELinux user label that applies to the container.
   * @type {string}
   * @memberof V1SELinuxOptions
   */
  user?: string
}
