// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.14.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KubeObject } from '../runtime'

/**
 * The node this Taint is attached to has the \"effect\" on any pod that does not tolerate the Taint.
 * @export
 * @interface V1Taint
 */
export default interface V1Taint extends KubeObject {
  /**
   * Required. The effect of the taint on pods that do not tolerate the taint. Valid effects are NoSchedule, PreferNoSchedule and NoExecute.
   * @type {string}
   * @memberof V1Taint
   */
  effect: string

  /**
   * Required. The taint key to be applied to a node.
   * @type {string}
   * @memberof V1Taint
   */
  key: string

  /**
   * TimeAdded represents the time at which the taint was added. It is only written for NoExecute taints.
   * @type {Date}
   * @memberof V1Taint
   */
  timeAdded?: Date

  /**
   * Required. The taint value corresponding to the taint key.
   * @type {string}
   * @memberof V1Taint
   */
  value?: string
}
